kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
spec:
  storageClassName: scenarios-opensearch-storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
